In [36]:
import pandas as pd 
import numpy as np
import time

In [37]:
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [38]:
data2021_01 = pd.read_csv(r'D:\DTy_work\dataframe\User_portrait_data\to_data\data\user_2021_01.csv')

data2021_02 = pd.read_csv(r'D:\DTy_work\dataframe\User_portrait_data\to_data\data\user_2021_02.csv')

data2021_03 = pd.read_csv(r'D:\DTy_work\dataframe\User_portrait_data\to_data\data\user_2021_03.csv')

data2021_04 = pd.read_csv(r'D:\DTy_work\dataframe\User_portrait_data\to_data\data\user_2021_04.csv')

data2021_05 = pd.read_csv(r'D:\DTy_work\dataframe\User_portrait_data\to_data\data\user_2021_05.csv')

data2021_06 = pd.read_csv(r'D:\DTy_work\dataframe\User_portrait_data\to_data\data\user_2021_06.csv')

data2021_07 = pd.read_csv(r'D:\DTy_work\dataframe\User_portrait_data\to_data\data\user_2021_07.csv')

data2021_08 = pd.read_csv(r'D:\DTy_work\dataframe\User_portrait_data\to_data\data\user_2021_08.csv')

data2021_09 = pd.read_csv(r'D:\DTy_work\dataframe\User_portrait_data\to_data\data\user_2021_09.csv')

data2021_10 = pd.read_csv(r'D:\DTy_work\dataframe\User_portrait_data\to_data\data\user_2021_10.csv')

data2021_11 = pd.read_csv(r'D:\DTy_work\dataframe\User_portrait_data\to_data\data\user_2021_11.csv')

data2021_12 = pd.read_csv(r'D:\DTy_work\dataframe\User_portrait_data\to_data\data\user_2021_12.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\DTy_work\\dataframe\\User_portrait_data\\to_data\\data\\user_2021_01.csv'

In [20]:
data2021_01

,Unnamed: 0,id,昵称,性别,等级,生日,年龄,兴趣ID,行业ID,直邀用户数,是否主办方,是否讲师,积分,是否游客,是否游客.1,连续登录天数,最大连续登录天数,上次登录时间,登陆时间,更新时间,省,市,区,累积学习时间/秒,最后一次学习时间,连续学习天数,学习课程数,加入时间,姓名,电话,线上/线下会务,会务订单总数,线上会务订单数,线下会务订单数,身份证号,new_time,register_time,born,count
0,0,757216,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-01-01 00:00:56,2021-01-01 00:00:56,2021-01-01 00:00:56,江苏省,常州市,NaN,0,NaN,0,0,2021-01-01 00:00:56.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:48.248527,446,2022,1
1,1,757217,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-01-01 00:01:00,2021-01-01 00:01:00,2021-01-01 00:01:00,广东省,东莞市,NaN,0,NaN,0,0,2021-01-01 00:01:00.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:48.248527,446,2022,1
2,2,757218,为善最乐,2,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-01-01 00:01:51,2021-01-11 11:44:23,2021-01-11 11:44:23,北京市,北京市,NaN,0,NaN,0,0,2021-01-01 00:01:51.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:48.248527,446,2022,1
3,3,757219,幸运权嫂,2,1,0,0,0,0,0,0,0,0,0,0,1,2,2021-01-02 13:46:32,2021-01-04 12:27:09,2021-01-04 12:27:09,广西壮族自治区,桂林市,NaN,0,NaN,0,0,2021-01-01 00:01:59.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:48.248527,446,2022,1
4,4,757220,水北卢氏养蜂场批发零售蜂产品,1,1,0,0,0,0,0,0,0,0,0,0,1,2,2021-01-11 13:02:40,2021-01-19 10:33:54,2021-01-19 10:33:54,江西省,萍乡市,NaN,336,2021-01-11,1,1,2021-01-01 00:03:35.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:48.248527,446,2022,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92768,92768,850002,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-01-31 23:54:10,2021-01-31 23:54:10,2021-01-31 23:54:10,新疆维吾尔自治区,伊犁哈萨克自治州,NaN,0,NaN,0,0,2021-01-31 23:54:10.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:48.248527,415,2022,1
92769,92769,850003,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-01-31 23:55:27,2021-01-31 23:55:27,2021-01-31 23:55:27,江苏省,南京市,NaN,0,NaN,0,0,2021-01-31 23:55:27.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:48.248527,415,2022,1
92770,92770,850004,百里守约,0,1,2007-01-02,0,0,0,0,0,0,0,0,0,1,2,2021-03-18 16:04:45,2021-03-18 16:38:36,2021-03-18 16:38:36,广东省,佛山市,NaN,1479,2021-02-01,1,2,2021-01-31 23:55:49.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:48.248527,415,2022,1
92771,92771,850005,罗春芸,2,1,0,38,0,0,0,0,0,4,0,0,1,2,2021-09-01 21:21:15,2022-01-19 12:40:11,2022-01-19 12:40:11,海南省,海口市,NaN,7475,2022-01-19,1,25,2021-01-31 23:58:01.000000,罗卿芸,13138951343,1.0,3.0,0.0,3.0,440881198402155145,2022-03-23 13:52:48.248527,415,1984,1
92772,92772,850006,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-01-31 23:59:51,2021-01-31 23:59:51,2021-01-31 23:59:51,重庆市,重庆市,NaN,0,NaN,0,0,2021-01-31 23:59:51.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:48.248527,415,2022,1

In [10]:
data2021_02.head()

,Unnamed: 0,id,昵称,性别,等级,生日,年龄,兴趣ID,行业ID,直邀用户数,是否主办方,是否讲师,积分,是否游客,是否游客.1,连续登录天数,最大连续登录天数,上次登录时间,登陆时间,更新时间,省,市,区,累积学习时间/秒,最后一次学习时间,连续学习天数,学习课程数,加入时间,姓名,电话,线上/线下会务,会务订单总数,线上会务订单数,线下会务订单数,身份证号,new_time,register_time,born,count
0,0,850007,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-02-01 00:03:25,2021-02-01 00:03:54,2021-02-01 00:03:54,湖南省,长沙市,NaN,0,NaN,0,0,2021-02-01 00:03:25.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:59.040235,415,2022,1
1,1,850008,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-02-01 00:03:34,2021-02-01 00:03:34,2021-02-01 00:03:34,广西壮族自治区,南宁市,NaN,0,NaN,0,0,2021-02-01 00:03:34.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:59.040235,415,2022,1
2,2,850009,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-02-01 00:10:09,2021-02-11 21:31:43,2021-02-11 21:31:43,广东省,广州市,NaN,0,NaN,0,0,2021-02-01 00:03:48.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:59.040235,415,2022,1
3,3,850010,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-02-01 00:11:54,2021-02-01 00:11:54,2021-02-01 00:11:54,新疆维吾尔自治区,伊犁哈萨克自治州,NaN,0,NaN,0,0,2021-02-01 00:11:54.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:59.040235,415,2022,1
4,4,850011,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-02-01 00:14:07,2021-02-01 00:14:07,2021-02-01 00:14:07,广东省,深圳市,NaN,0,NaN,0,0,2021-02-01 00:14:07.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:52:59.040235,415,2022,1

In [11]:
data2021_03.head()

,Unnamed: 0,id,昵称,性别,等级,生日,年龄,兴趣ID,行业ID,直邀用户数,是否主办方,是否讲师,积分,是否游客,是否游客.1,连续登录天数,最大连续登录天数,上次登录时间,登陆时间,更新时间,省,市,区,累积学习时间/秒,最后一次学习时间,连续学习天数,学习课程数,加入时间,姓名,电话,线上/线下会务,会务订单总数,线上会务订单数,线下会务订单数,身份证号,new_time,register_time,born,count
0,0,923019,17601006036,0,1,1985-01-16,0,0,0,0,0,0,0,0,0,1,1,2021-03-01 00:08:37,2021-03-01 00:14:30,2021-03-01 00:15:48,宁夏回族自治区,银川市,NaN,0,NaN,0,0,2021-03-01 00:08:37.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:10.056021,387,2022,1
1,1,923020,18392399071,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-03-01 00:11:38,2021-03-01 00:11:38,2021-03-01 00:11:38,陕西省,汉中市,NaN,0,NaN,0,0,2021-03-01 00:11:38.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:10.056021,387,2022,1
2,2,923021,18259906008,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-03-01 00:15:28,2021-03-01 00:15:28,2021-03-01 00:15:28,福建省,NaN,NaN,0,NaN,0,0,2021-03-01 00:15:28.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:10.056021,387,2022,1
3,3,923022,15673530499,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-03-01 00:17:08,2021-03-01 00:17:08,2021-03-01 00:17:08,湖南省,长沙市,NaN,0,NaN,0,0,2021-03-01 00:17:08.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:10.056021,387,2022,1
4,4,923023,13556500818,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-12-03 09:04:42,2021-12-03 09:04:57,2021-12-03 09:04:57,广东省,NaN,NaN,0,NaN,0,0,2021-03-01 00:21:35.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:10.056021,387,2022,1

In [12]:
data2021_04.head()

,Unnamed: 0,id,昵称,性别,等级,生日,年龄,兴趣ID,行业ID,直邀用户数,是否主办方,是否讲师,积分,是否游客,是否游客.1,连续登录天数,最大连续登录天数,上次登录时间,登陆时间,更新时间,省,市,区,累积学习时间/秒,最后一次学习时间,连续学习天数,学习课程数,加入时间,姓名,电话,线上/线下会务,会务订单总数,线上会务订单数,线下会务订单数,身份证号,new_time,register_time,born,count
0,0,1031608,18153791128,1,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-06-29 08:06:32,2021-07-04 13:34:09,2021-07-04 13:34:09,湖南省,长沙市,NaN,127,2021-04-01,1,1,2021-04-01 00:00:28.000000,18153791128,18153791128,2.0,1.0,1.0,0.0,0,2022-03-23 13:53:16.209844,356,2022,1
1,1,1031609,13911257987,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-04-01 00:01:25,2021-04-01 00:01:25,2021-04-01 00:01:25,北京市,北京市,NaN,0,NaN,0,0,2021-04-01 00:01:25.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,356,2022,1
2,2,1031610,17748644813,1,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-04-01 00:02:49,2021-04-01 00:02:49,2021-04-01 00:02:49,广东省,深圳市,NaN,0,NaN,0,0,2021-04-01 00:02:49.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,356,2022,1
3,3,1031611,13170951689,2,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-04-04 12:37:41,2021-04-06 17:38:53,2021-04-06 17:38:53,江西省,南昌市,NaN,104,2021-04-01,1,1,2021-04-01 00:03:04.000000,周志艳,13170951689,1.0,2.0,0.0,2.0,0,2022-03-23 13:53:16.209844,356,2022,1
4,4,1031612,13974123848,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-04-01 00:06:08,2021-04-01 00:06:08,2021-04-01 00:06:08,湖南省,长沙市,NaN,0,NaN,0,0,2021-04-01 00:06:08.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,356,2022,1

In [13]:
data2021_05.head()

,Unnamed: 0,id,昵称,性别,等级,生日,年龄,兴趣ID,行业ID,直邀用户数,是否主办方,是否讲师,积分,是否游客,是否游客.1,连续登录天数,最大连续登录天数,上次登录时间,登陆时间,更新时间,省,市,区,累积学习时间/秒,最后一次学习时间,连续学习天数,学习课程数,加入时间,姓名,电话,线上/线下会务,会务订单总数,线上会务订单数,线下会务订单数,身份证号,new_time,register_time,born,count
0,0,1536619,13246402819,0,0,0,0,0,0.0,0,0,0,0,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,2021-05-01 00:00:12,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 14:02:24.176963,326,2022,1
1,1,1536620,18998474892,0,0,0,0,0,0.0,0,0,0,0,0,0,1,1,2022-03-16 21:02:38,2022-03-16 21:03:29,2022-03-16 21:03:29,广东省,广州市,NaN,0,0,0,0,2021-05-01 00:01:54,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 14:02:24.176963,326,2022,1
2,2,1536621,13237080655,0,0,0,0,0,0.0,0,0,0,0,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,2021-05-01 00:20:43,13237080655,13237080655,1.0,1.0,0.0,1.0,0,2022-03-23 14:02:24.176963,326,2022,1
3,3,1536622,15816084084,0,0,0,0,0,0.0,0,0,0,0,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,2021-05-01 01:04:58,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 14:02:24.176963,326,2022,1
4,4,1536623,13815717287,0,0,0,0,0,0.0,0,0,0,0,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,2021-05-01 01:22:40,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 14:02:24.176963,326,2022,1

In [14]:
data2021_11.head()

,Unnamed: 0,id,昵称,性别,等级,生日,年龄,兴趣ID,行业ID,直邀用户数,是否主办方,是否讲师,积分,是否游客,是否游客.1,连续登录天数,最大连续登录天数,上次登录时间,登陆时间,更新时间,省,市,区,累积学习时间/秒,最后一次学习时间,连续学习天数,学习课程数,加入时间,姓名,电话,线上/线下会务,会务订单总数,线上会务订单数,线下会务订单数,身份证号,new_time,register_time,born,count
0,0,1748736,13760634783,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-11-01 00:05:13,2021-11-01 00:05:13,2021-11-01 00:05:13,广东省,肇庆市,NaN,0,NaN,0,0,2021-11-01 00:05:13.000000,13760634783,13760634783,2.0,1.0,1.0,0.0,0,2022-03-23 13:56:49.638797,142,2022,1
1,1,1748737,19123590922,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-11-01 00:29:22,2021-11-01 00:29:22,2021-11-01 00:29:22,北京市,北京市,NaN,0,NaN,0,0,2021-11-01 00:29:22.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:56:49.638797,142,2022,1
2,2,1748738,15085589925,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-11-01 00:36:17,2021-11-01 00:36:38,2021-11-01 00:36:38,贵州省,遵义市,NaN,0,NaN,0,0,2021-11-01 00:36:16.000000,15085589925,15085589925,2.0,1.0,1.0,0.0,0,2022-03-23 13:56:49.638797,142,2022,1
3,3,1748739,13503248485,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-11-01 00:57:13,2021-11-01 01:02:46,2021-11-01 01:02:46,河北省,廊坊市,NaN,0,NaN,0,0,2021-11-01 00:57:13.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:56:49.638797,142,2022,1
4,4,1748740,13157073030,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-11-01 01:02:00,2021-11-01 01:02:57,2021-11-01 01:02:57,安徽省,淮北市,NaN,0,NaN,0,0,2021-11-01 01:01:31.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:56:49.638797,142,2022,1

In [29]:
data = pd.DataFrame()

In [30]:
data = pd.concat([data,data2021_01],axis=0)
data = pd.concat([data,data2021_02],axis=0)
data = pd.concat([data,data2021_03],axis=0)
data = pd.concat([data,data2021_04],axis=0)
data = pd.concat([data,data2021_05],axis=0)
data = pd.concat([data,data2021_06],axis=0)
data = pd.concat([data,data2021_07],axis=0)
data = pd.concat([data,data2021_08],axis=0)
data = pd.concat([data,data2021_09],axis=0)
data = pd.concat([data,data2021_10],axis=0)
data = pd.concat([data,data2021_11],axis=0)
data = pd.concat([data,data2021_12],axis=0)

In [46]:
data2021_04[data2021_04['线上/线下会务'] == 0 ]

,Unnamed: 0,id,昵称,性别,等级,生日,年龄,兴趣ID,行业ID,直邀用户数,是否主办方,是否讲师,积分,是否游客,是否游客.1,连续登录天数,最大连续登录天数,上次登录时间,登陆时间,更新时间,省,市,区,累积学习时间/秒,最后一次学习时间,连续学习天数,学习课程数,加入时间,姓名,电话,线上/线下会务,会务订单总数,线上会务订单数,线下会务订单数,身份证号,new_time,register_time,born,count
1,1,1031609,13911257987,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-04-01 00:01:25,2021-04-01 00:01:25,2021-04-01 00:01:25,北京市,北京市,NaN,0,NaN,0,0,2021-04-01 00:01:25.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,356,2022,1
2,2,1031610,17748644813,1,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-04-01 00:02:49,2021-04-01 00:02:49,2021-04-01 00:02:49,广东省,深圳市,NaN,0,NaN,0,0,2021-04-01 00:02:49.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,356,2022,1
4,4,1031612,13974123848,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-04-01 00:06:08,2021-04-01 00:06:08,2021-04-01 00:06:08,湖南省,长沙市,NaN,0,NaN,0,0,2021-04-01 00:06:08.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,356,2022,1
5,5,1031613,17782283236,0,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-04-01 00:06:59,2021-04-01 00:06:59,2021-04-01 00:06:59,重庆市,重庆市,NaN,0,NaN,0,0,2021-04-01 00:06:59.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,356,2022,1
6,6,1031614,18869951587,2,1,0,0,0,0,0,0,0,0,0,0,1,1,2021-04-01 00:21:17,2021-04-01 01:05:13,2021-04-01 01:05:13,浙江省,宁波市,NaN,0,NaN,0,0,2021-04-01 00:09:32.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,356,2022,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36229,36229,1536614,15277899185,0,0,0,0,0,0,0,0,0,0,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,2021-04-30 23:29:31.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,326,2022,1
36230,36230,1536615,15068840455,0,0,0,0,0,0,0,0,0,0,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,2021-04-30 23:33:38.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,326,2022,1
36231,36231,1536616,15100668252,0,0,0,0,0,0,0,0,0,0,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,2021-04-30 23:42:50.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,326,2022,1
36232,36232,1536617,13098687778,0,0,0,0,0,0,0,0,0,0,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,2021-04-30 23:43:03.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,326,2022,1
36233,36233,1536618,13709081471,0,0,0,0,0,0,0,0,0,0,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,2021-04-30 23:48:35.000000,未知,0,0.0,NaN,NaN,NaN,0,2022-03-23 13:53:16.209844,326,2022,1